import {semitoneDistance,playbackRatio,centsFromSemitones,bpmAfterPitchShift,stretchPercent,noteDurations,loopDuration,impliedBpm,driftMs,camelotForKey,openKeyForKey,noteFrequency,frequencyToNote,semitonesFromRatio,allTargets} from './music.js';
const $=id=>document.getElementById(id);const keysSharp=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];const keysFlat=['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B'];const stateFields=['sourceKey','targetKey','sourceBpm','targetBpm','sourceQuality','targetQuality','direction','notation'];const fmt=(n,d=2)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';const signed=(n,d=2,suffix='')=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${Number(n).toFixed(d)}${suffix}`:'—';
function fillKeySelect(select,selected,notation='sharp'){const arr=notation==='flat'?keysFlat:keysSharp;select.innerHTML=arr.map(k=>`<option value="${k}">${k}</option>`).join('');if(arr.includes(selected))select.value=selected}
function metric(label,value){return `<div class="metric"><span>${label}</span><strong>${value}</strong></div>`}
function updateUrl(){const p=new URLSearchParams();for(const id of stateFields)p.set(id,$(id).value);history.replaceState(null,'',`${location.pathname}?${p.toString()}${location.hash}`)}
function readUrl(){const p=new URLSearchParams(location.search);for(const id of stateFields)if(p.has(id)&&$(id))$(id).value=p.get(id)}
function renderMain(){try{const source=$('sourceKey').value,target=$('targetKey').value;const semis=semitoneDistance(source,target,$('direction').value);const ratio=playbackRatio(semis);const sbpm=Number($('sourceBpm').value),tbpm=Number($('targetBpm').value);const speedBpm=sbpm>0?bpmAfterPitchShift(sbpm,semis):NaN;const stretch=sbpm>0&&tbpm>0?stretchPercent(sbpm,tbpm):NaN;const remainingStretch=speedBpm>0&&tbpm>0?stretchPercent(speedBpm,tbpm):NaN;$('mainResults').innerHTML=[metric('Pitch shift',signed(semis,0,' st')),metric('Cents',signed(centsFromSemitones(semis),0,'¢')),metric('Playback rate',`${fmt(ratio,6)}×`),metric('Speed change',signed((ratio-1)*100,2,'%')),metric('BPM if linked',fmt(speedBpm,2)),metric('Independent stretch',signed(stretch,2,'%')),metric('Source Camelot',camelotForKey(source,$('sourceQuality').value)),metric('Target Camelot',camelotForKey(target,$('targetQuality').value)),metric('Source Open Key',openKeyForKey(source,$('sourceQuality').value)),metric('Target Open Key',openKeyForKey(target,$('targetQuality').value)),metric('Stretch after pitch-rate',signed(remainingStretch,2,'%')),metric('Rate duration factor',`${fmt(1/ratio,4)}×`)].join('');$('workflowNote').textContent=Math.abs(remainingStretch)<.01?'A single playback-rate change reaches both the selected key and target BPM.':`A single playback-rate change reaches ${fmt(speedBpm,2)} BPM. To also reach ${fmt(tbpm,2)} BPM, pitch/speed must be treated independently or followed by about ${signed(remainingStretch,2,'%')} time-stretch.`;$('targetsBody').innerHTML=allTargets(source,sbpm,$('notation').value).map(r=>`<tr><td>${r.target}</td><td>${signed(r.semitones,0)}</td><td>${signed(r.cents,0)}</td><td>${fmt(r.ratio,6)}×</td><td>${signed(r.percent,2,'%')}</td><td>${fmt(r.resultingBpm,2)}</td></tr>`).join('');updateUrl()}catch(e){$('mainResults').innerHTML=metric('Input error',e.message)}}
function renderTiming(){try{const bpm=Number($('timingBpm').value),bars=Number($('bars').value),beats=Number($('beatsPerBar').value),seconds=Number($('observedSeconds').value);const n=noteDurations(bpm);$('timingResults').innerHTML=[metric('1 beat',`${fmt(n.quarterMs,2)} ms`),metric(`${bars} bars`,`${fmt(loopDuration(bpm,bars,beats),3)} s`),metric('Implied BPM',fmt(impliedBpm(seconds,bars,beats),3))].join('');const rows=[['Whole',n.wholeMs],['Half',n.halfMs],['Quarter',n.quarterMs],['Eighth',n.eighthMs],['Sixteenth',n.sixteenthMs],['Dotted quarter',n.dottedQuarterMs],['Dotted eighth',n.dottedEighthMs],['Quarter triplet',n.quarterTripletMs],['Eighth triplet',n.eighthTripletMs]];$('noteBody').innerHTML=rows.map(([name,v])=>`<tr><td>${name}</td><td>${fmt(v,3)}</td></tr>`).join('')}catch(e){$('timingResults').innerHTML=metric('Input error',e.message)}}
function renderDrift(){try{const s=Number($('driftSource').value),t=Number($('driftTarget').value),b=Number($('driftBars').value),beats=Number($('driftBeats').value);const ms=driftMs(s,t,b,beats);const beatMs=60000/t;$('driftResults').innerHTML=[metric('Drift',signed(ms,2,' ms')),metric('Drift in beats',signed(ms/beatMs,4)),metric('Loop length',`${fmt(loopDuration(s,b,beats),3)} s`),metric('Project length',`${fmt(loopDuration(t,b,beats),3)} s`)].join('')}catch(e){$('driftResults').innerHTML=metric('Input error',e.message)}}
function renderReverse(){try{const r=Number($('reverseRate').value);const st=semitonesFromRatio(r);$('reverseResult').textContent=`${signed(st,3,' semitones')} · ${signed(st*100,1,' cents')} · ${signed((r-1)*100,3,'% speed')}`}catch(e){$('reverseResult').textContent=e.message}}
function renderFrequency(){try{const a=Number($('a4').value),f=noteFrequency($('freqNote').value,Number($('freqOctave').value),a),inspected=frequencyToNote(Number($('inspectFreq').value),a,$('notation').value);$('frequencyResult').textContent=`Selected note: ${fmt(f,3)} Hz · ${$('inspectFreq').value} Hz ≈ ${inspected.note} (${signed(inspected.cents,2,'¢')})`}catch(e){$('frequencyResult').textContent=e.message}}
function syncNotation(){const notation=$('notation').value;const oldS=$('sourceKey').selectedIndex,oldT=$('targetKey').selectedIndex,oldF=$('freqNote').selectedIndex;fillKeySelect($('sourceKey'),(notation==='flat'?keysFlat:keysSharp)[Math.max(0,oldS)],notation);fillKeySelect($('targetKey'),(notation==='flat'?keysFlat:keysSharp)[Math.max(0,oldT)],notation);fillKeySelect($('freqNote'),(notation==='flat'?keysFlat:keysSharp)[Math.max(0,oldF)],notation)}
let taps=[];$('tapButton').addEventListener('click',()=>{const now=performance.now();if(taps.length&&now-taps.at(-1)>2500)taps=[];taps.push(now);if(taps.length>8)taps.shift();if(taps.length>1){const intervals=taps.slice(1).map((v,i)=>v-taps[i]);const avg=intervals.reduce((a,b)=>a+b,0)/intervals.length;$('tapBpm').textContent=fmt(60000/avg,1)}});$('tapReset').addEventListener('click',()=>{taps=[];$('tapBpm').textContent='—'});
fillKeySelect($('sourceKey'),'F#');fillKeySelect($('targetKey'),'A');fillKeySelect($('freqNote'),'A');readUrl();for(const id of stateFields)$(id).addEventListener('input',()=>{if(id==='notation')syncNotation();renderMain();renderFrequency()});['timingBpm','bars','beatsPerBar','observedSeconds'].forEach(id=>$(id).addEventListener('input',renderTiming));['driftSource','driftTarget','driftBars','driftBeats'].forEach(id=>$(id).addEventListener('input',renderDrift));$('reverseRate').addEventListener('input',renderReverse);['freqNote','freqOctave','a4','inspectFreq'].forEach(id=>$(id).addEventListener('input',renderFrequency));renderMain();renderTiming();renderDrift();renderReverse();renderFrequency();
